# -*- coding: utf-8 -*-
"""criteria_weight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd

def show_criteria_weight():

    st.title("⚖️ Criteria Weight")

    # =====================================
    # CHECK PAYOFF MATRIX
    # =====================================

    if (
        "payoff_df" not in st.session_state
        or st.session_state["payoff_df"] is None
    ):

        st.warning(
            "⚠️ Generate payoff matrix first."
        )

        return

    payoff_df = st.session_state["payoff_df"]

    # =====================================
    # INITIALIZE WEIGHTS
    # =====================================

    weights = {}

    total = 0

    st.subheader(
        "📊 Set Criteria Weights"
    )

    # =====================================
    # WEIGHT INPUT
    # =====================================

    for col in payoff_df.columns:

        default_value = round(
            1 / len(payoff_df.columns),
            2
        )

        weight = st.slider(
            f"{col}",
            0.0,
            1.0,
            default_value,
            0.01,
            key=f"weight_{col}"
        )

        weights[col] = weight

        total += weight

    # =====================================
    # TOTAL WEIGHT CHECK
    # =====================================

    st.info(
        f"Total Weight = {round(total,2)}"
    )

    if round(total,2) != 1.0:

        st.error(
            "⚠️ Total weight must equal 1.0"
        )

        return

    # =====================================
    # CRITERIA TYPE
    # =====================================

    criteria_type = {}

    st.subheader(
        "⚖️ Criteria Type"
    )

    for col in payoff_df.columns:

        criteria_type[col] = st.selectbox(
            f"{col} Type",
            [
                "Benefit",
                "Cost"
            ],
            key=f"type_{col}"
        )

    # =====================================
    # WEIGHTED MATRIX
    # =====================================

    weighted_df = payoff_df.copy()

    for col in weighted_df.columns:

        if criteria_type[col] == "Cost":

            weighted_df[col] = (
                1 /
                (weighted_df[col] + 1e-9)
            )

        weighted_df[col] = (
            weighted_df[col]
            * weights[col]
        )

    # =====================================
    # SAVE SESSION
    # =====================================

    st.session_state[
        "criteria_weights"
    ] = weights

    st.session_state[
        "criteria_type"
    ] = criteria_type

    st.session_state[
        "weighted_payoff_df"
    ] = weighted_df

    # =====================================
    # OUTPUT
    # =====================================

    st.success(
        "✅ Weighted Matrix Saved"
    )

    st.dataframe(
        weighted_df,
        use_container_width=True
    )