# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st

def show_dashboard():

    st.title("🤎 Business Location DSS")

    st.write("""
    Sistem Pendukung Keputusan
    untuk menentukan lokasi usaha terbaik
    menggunakan berbagai metode DSS.
    """)

    # =====================================
    # CHECK SESSION
    # =====================================

    if (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
    ):

        total_loc = len(
            st.session_state["payoff_df"]
        )

        total_state = len(
            st.session_state["payoff_df"].columns
        )

        status = "Connected"

    else:

        total_loc = 0
        total_state = 0
        status = "Waiting"

    # =====================================
    # METRICS
    # =====================================

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("📊 Modules", 10)

    with col2:
        st.metric("📍 Locations", total_loc)

    with col3:
        st.metric("🌎 Criteria", total_state)

    with col4:
        st.metric("🏆 Status", status)

    # =====================================
    # WORKFLOW
    # =====================================

    st.subheader("🚀 Workflow")

    st.info("""
    1. Upload dataset

    2. Generate payoff matrix

    3. Set criteria weights

    4. Run EV & EOL analysis

    5. Analyze uncertainty

    6. Distribution analysis

    7. Utility analysis

    8. Monte Carlo simulation

    9. Final recommendation
    """)

    # =====================================
    # CONNECTION STATUS
    # =====================================

    st.subheader("🔗 System Connection")

    if status == "Connected":

        st.success("""
        ✅ Dataset Connected
        ✅ Payoff Matrix Connected
        ✅ All DSS Modules Connected
        """)

    else:

        st.warning("""
        ⚠️ Upload dataset terlebih dahulu untuk menghubungkan semua module DSS.
        """)