# -*- coding: utf-8 -*-
"""data_driven.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# =====================================
# NORMALIZATION FUNCTION
# =====================================

def normalize_data(df):

    normalized_df = df.copy()

    for col in normalized_df.columns:

        min_val = normalized_df[col].min()
        max_val = normalized_df[col].max()

        if max_val - min_val != 0:

            normalized_df[col] = (
                (normalized_df[col] - min_val)
                /
                (max_val - min_val)
            )

    return normalized_df


# =====================================
# MAIN PAGE
# =====================================

def show_data_driven():

    st.title("📊 Data-Driven DSS")

    # =====================================
    # SESSION STATE
    # =====================================

    if "uploaded_df" not in st.session_state:
        st.session_state["uploaded_df"] = None

    if "payoff_df" not in st.session_state:
        st.session_state["payoff_df"] = None

    # =====================================
    # FILE UPLOADER
    # =====================================

    uploaded_file = st.file_uploader(
        "Upload Dataset",
        type=["csv", "xlsx"]
    )

    if uploaded_file is not None:

        try:

            if uploaded_file.name.endswith(".csv"):

                df = pd.read_csv(uploaded_file)

            else:

                df = pd.read_excel(uploaded_file)

            st.session_state["uploaded_df"] = df

            st.success(
                "✅ Dataset uploaded"
            )

        except Exception as e:

            st.error(f"❌ Error: {e}")

            return

    df = st.session_state["uploaded_df"]

    # =====================================
    # CHECK DATA
    # =====================================

    if df is not None:

        # =====================================
        # DATASET PREVIEW
        # =====================================

        st.subheader("📋 Dataset Preview")

        st.dataframe(
            df,
            use_container_width=True
        )

        # =====================================
        # BASIC INFO
        # =====================================

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Rows",
                df.shape[0]
            )

        with col2:
            st.metric(
                "Columns",
                df.shape[1]
            )

        with col3:
            st.metric(
                "Numeric Features",
                len(
                    df.select_dtypes(
                        include="number"
                    ).columns
                )
            )

        numeric_cols = df.select_dtypes(
            include="number"
        ).columns

        # =====================================
        # DESCRIPTIVE STATISTICS
        # =====================================

        st.subheader(
            "📈 Descriptive Statistics"
        )

        st.dataframe(
            df.describe(),
            use_container_width=True
        )

        # =====================================
        # HISTOGRAM
        # =====================================

        st.subheader(
            "📊 Histogram Visualization"
        )

        selected_hist = st.selectbox(
            "Select Histogram Column",
            numeric_cols
        )

        fig_hist = px.histogram(
            df,
            x=selected_hist,
            color_discrete_sequence=["#6F4E37"]
        )

        st.plotly_chart(
            fig_hist,
            use_container_width=True
        )

        # =====================================
        # LOCATION COLUMN
        # =====================================

        location_col = st.selectbox(
            "Select Location Column",
            df.columns
        )

        # =====================================
        # BAR CHART
        # =====================================

        st.subheader(
            "📉 Bar Chart Visualization"
        )

        selected_bar = st.selectbox(
            "Select Bar Chart Column",
            numeric_cols,
            key="bar"
        )

        bar_data = (
            df.groupby(location_col)[selected_bar]
            .mean()
            .reset_index()
        )

        fig_bar = px.bar(
            bar_data,
            x=location_col,
            y=selected_bar,
            color=selected_bar,
            color_continuous_scale="Brwnyl"
        )

        st.plotly_chart(
            fig_bar,
            use_container_width=True
        )

        # =====================================
        # HEATMAP
        # =====================================

        st.subheader(
            "🔥 Correlation Heatmap"
        )

        corr = df[numeric_cols].corr()

        fig_heatmap = px.imshow(
            corr,
            text_auto=True,
            color_continuous_scale="Brwnyl"
        )

        st.plotly_chart(
            fig_heatmap,
            use_container_width=True
        )

        # =====================================
        # PAYOFF MATRIX
        # =====================================

        st.subheader(
            "🔄 Generate Payoff Matrix"
        )

        selected_metrics = st.multiselect(
            "Select Criteria",
            numeric_cols,
            default=list(numeric_cols[:3])
        )

        normalization = st.checkbox(
            "Apply Normalization"
        )

        if st.button(
            "Generate Payoff Matrix"
        ):

            payoff_df = df.set_index(
                location_col
            )[selected_metrics]

            if normalization:

                payoff_df = normalize_data(
                    payoff_df
                )

            st.session_state[
                "payoff_df"
            ] = payoff_df

            st.session_state[
                "alternatives"
            ] = payoff_df.index.tolist()

            st.session_state[
                "states"
            ] = payoff_df.columns.tolist()

            st.success(
                "✅ Payoff Matrix Generated"
            )

            st.subheader(
                "📋 Generated Payoff Matrix"
            )

            st.dataframe(
                payoff_df,
                use_container_width=True
            )

    else:

        st.info(
            "📂 Please upload dataset first."
        )