# -*- coding: utf-8 -*-
"""distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import numpy as np
import plotly.express as px

def show_distribution():

    st.title("📈 Distribution Analysis")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    # =====================================
    # LOCATION SELECTION
    # =====================================

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    data = payoff_df.loc[location].values

    # =====================================
    # METRICS
    # =====================================

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Mean",
            round(np.mean(data),4)
        )

    with col2:

        st.metric(
            "Standard Deviation",
            round(np.std(data),4)
        )

    # =====================================
    # HISTOGRAM
    # =====================================

    fig = px.histogram(
        x=data,
        nbins=10,
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Weighted Payoff",
        yaxis_title="Frequency"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # =====================================
    # STATUS
    # =====================================

    st.success(
        "✅ Distribution analysis completed"
    )