# -*- coding: utf-8 -*-
"""ev_eol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

def show_ev_eol():

    st.title("🎲 EV & EOL Analysis")

    # =====================================
    # CHECK WEIGHTS
    # =====================================

    if (
        "criteria_weights" not in st.session_state
    ):

        st.warning(
            "⚠️ Configure criteria weights first."
        )

        return

    # =====================================
    # USE WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    # =====================================
    # GET WEIGHTS
    # =====================================

    weights = list(
        st.session_state[
            "criteria_weights"
        ].values()
    )

    # =====================================
    # DISPLAY MATRIX
    # =====================================

    st.subheader(
        "📊 Weighted Matrix"
    )

    st.dataframe(
        payoff_df,
        use_container_width=True
    )

    # =====================================
    # EXPECTED VALUE
    # =====================================

    ev = payoff_df.dot(weights)

    ev_df = pd.DataFrame({

        "Alternative": payoff_df.index,

        "EV": np.round(
            ev.values,
            4
        )

    })

    ev_df = ev_df.sort_values(
        by="EV",
        ascending=False
    )

    st.subheader(
        "🎯 Expected Value"
    )

    st.dataframe(
        ev_df,
        use_container_width=True
    )

    # =====================================
    # EOL
    # =====================================

    regret = payoff_df.max() - payoff_df

    eol = regret.dot(weights)

    eol_df = pd.DataFrame({

        "Alternative": payoff_df.index,

        "EOL": np.round(
            eol.values,
            4
        )

    })

    eol_df = eol_df.sort_values(
        by="EOL",
        ascending=True
    )

    st.subheader(
        "📉 Expected Opportunity Loss"
    )

    st.dataframe(
        eol_df,
        use_container_width=True
    )

    # =====================================
    # BEST RESULT
    # =====================================

    st.success(
        f"🏆 Best EV : {ev.idxmax()}"
    )

    st.success(
        f"🏆 Best EOL : {eol.idxmin()}"
    )

    # =====================================
    # SAVE RESULT
    # =====================================

    st.session_state[
        "ev_result"
    ] = ev.idxmax()

    st.session_state[
        "eol_result"
    ] = eol.idxmin()