# -*- coding: utf-8 -*-
"""monte_carlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import numpy as np
import plotly.express as px

def show_monte_carlo():

    st.title("🎰 Monte Carlo Simulation")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    # =====================================
    # LOCATION SELECTION
    # =====================================

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    values = payoff_df.loc[location].values

    # =====================================
    # NUMBER OF SIMULATIONS
    # =====================================

    simulations = st.slider(
        "Number of Simulations",
        100,
        10000,
        1000
    )

    # =====================================
    # MONTE CARLO PROCESS
    # =====================================

    simulated = np.random.normal(
        np.mean(values),
        np.std(values),
        simulations
    )

    # =====================================
    # METRICS
    # =====================================

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Expected Profit",
            round(np.mean(simulated),4)
        )

    with col2:

        st.metric(
            "Simulation Std",
            round(np.std(simulated),4)
        )

    # =====================================
    # HISTOGRAM
    # =====================================

    fig = px.histogram(
        simulated,
        nbins=40,
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Simulated Profit",
        yaxis_title="Frequency"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # =====================================
    # PROBABILITY OF PROFIT
    # =====================================

    prob_profit = (
        np.mean(simulated > 0)
        * 100
    )

    st.success(
        f"✅ Probability of Profit = {round(prob_profit,2)}%"
    )