# -*- coding: utf-8 -*-
"""payoff_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st

def show_payoff_table():

    st.title("📋 Payoff Table")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

        st.success(
            "✅ Using Weighted Matrix"
        )

    # =====================================
    # CHECK ORIGINAL MATRIX
    # =====================================

    elif (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "payoff_df"
        ]

        st.warning(
            "⚠️ Using Original Matrix"
        )

    # =====================================
    # NO DATA
    # =====================================

    else:

        st.warning(
            "⚠️ No payoff matrix available."
        )

        return

    # =====================================
    # DISPLAY TABLE
    # =====================================

    st.dataframe(
        payoff_df,
        use_container_width=True
    )