# -*- coding: utf-8 -*-
"""recommendation_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd

def show_recommendation():

    st.title("🏆 Recommendation Engine")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    # =====================================
    # GET WEIGHTS
    # =====================================

    weights = list(
        st.session_state[
            "criteria_weights"
        ].values()
    )

    # =====================================
    # MAXIMAX
    # =====================================

    maximax = payoff_df.max(axis=1)

    # =====================================
    # MAXIMIN
    # =====================================

    maximin = payoff_df.min(axis=1)

    # =====================================
    # LAPLACE
    # =====================================

    laplace = payoff_df.mean(axis=1)

    # =====================================
    # MINIMAX REGRET
    # =====================================

    regret = payoff_df.max() - payoff_df

    minimax = regret.max(axis=1)

    # =====================================
    # EXPECTED VALUE
    # =====================================

    ev = payoff_df.dot(weights)

    # =====================================
    # BEST RESULT EACH METHOD
    # =====================================

    best_maximax = maximax.idxmax()

    best_maximin = maximin.idxmax()

    best_laplace = laplace.idxmax()

    best_minimax = minimax.idxmin()

    best_ev = ev.idxmax()

    # =====================================
    # VOTING SYSTEM
    # =====================================

    votes = [

        best_maximax,

        best_maximin,

        best_laplace,

        best_minimax,

        best_ev

    ]

    result = pd.Series(
        votes
    ).value_counts()

    final_choice = result.idxmax()

    # =====================================
    # RESULT TABLE
    # =====================================

    df = pd.DataFrame({

        "Method": [

            "Maximax",

            "Maximin",

            "Laplace",

            "Minimax Regret",

            "Expected Value"

        ],

        "Recommendation": votes

    })

    # =====================================
    # DISPLAY RESULT
    # =====================================

    st.dataframe(
        df,
        use_container_width=True
    )

    # =====================================
    # FINAL RESULT
    # =====================================

    st.success(
        f"🏆 Final Recommendation : {final_choice}"
    )

    st.info(
        f"Selected by {result.max()} methods"
    )