# -*- coding: utf-8 -*-
"""uncertainty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd

def show_uncertainty():

    st.title("❓ Uncertainty Analysis")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    # =====================================
    # MAXIMAX
    # =====================================

    maximax = payoff_df.max(axis=1)

    # =====================================
    # MAXIMIN
    # =====================================

    maximin = payoff_df.min(axis=1)

    # =====================================
    # LAPLACE
    # =====================================

    laplace = payoff_df.mean(axis=1)

    # =====================================
    # MINIMAX REGRET
    # =====================================

    regret = payoff_df.max() - payoff_df

    minimax = regret.max(axis=1)

    # =====================================
    # RESULT TABLE
    # =====================================

    result = pd.DataFrame({

        "Location": payoff_df.index,

        "Maximax": maximax.values,

        "Maximin": maximin.values,

        "Laplace": laplace.values,

        "Minimax Regret": minimax.values

    })

    # =====================================
    # DISPLAY RESULT
    # =====================================

    st.dataframe(
        result,
        use_container_width=True
    )

    # =====================================
    # BEST RESULTS
    # =====================================

    st.success(
        f"🌟 Maximax : {maximax.idxmax()}"
    )

    st.success(
        f"🛡️ Maximin : {maximin.idxmax()}"
    )

    st.success(
        f"⚖️ Laplace : {laplace.idxmax()}"
    )

    st.success(
        f"📉 Minimax : {minimax.idxmin()}"
    )