# -*- coding: utf-8 -*-
"""utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px

def show_utility():

    st.title("⚖️ Utility Function")

    # =====================================
    # CHECK WEIGHTED MATRIX
    # =====================================

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    # =====================================
    # LOCATION SELECTION
    # =====================================

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    values = payoff_df.loc[location].values

    # =====================================
    # RISK PREFERENCE
    # =====================================

    risk = st.selectbox(
        "Risk Preference",
        [
            "Risk Averse",
            "Risk Neutral",
            "Risk Seeking"
        ]
    )

    # =====================================
    # GENERATE X
    # =====================================

    x = np.linspace(
        min(values),
        max(values),
        100
    )

    # =====================================
    # UTILITY FUNCTION
    # =====================================

    if risk == "Risk Averse":

        utility = np.sqrt(
            x - min(x) + 1
        )

    elif risk == "Risk Neutral":

        utility = x

    else:

        utility = (
            x - min(x) + 1
        ) ** 2

    # =====================================
    # DATAFRAME
    # =====================================

    df = pd.DataFrame({

        "Payoff": x,

        "Utility": utility

    })

    # =====================================
    # VISUALIZATION
    # =====================================

    fig = px.line(
        df,
        x="Payoff",
        y="Utility",
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Weighted Payoff",
        yaxis_title="Utility Value"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # =====================================
    # RESULT
    # =====================================

    st.success(
        f"✅ Expected Utility = {round(np.mean(utility),4)}"
    )