# -*- coding: utf-8 -*-
"""sidebar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
import pandas as pd

def sidebar_menu():

    st.sidebar.title("🤎 Navigation")

    menu = st.sidebar.radio(
        "Select Module",
        [
            "🏠 Dashboard",
            "📊 Data-Driven DSS",
            "⚖️ Criteria Weight",
            "📋 Payoff Table",
            "🎲 EV & EOL",
            "❓ Uncertainty",
            "📈 Distribution",
            "⚖️ Utility Function",
            "🎰 Monte Carlo",
            "🏆 Recommendation"
        ]
    )

    st.sidebar.markdown("---")

    payoff_exists = (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
        and isinstance(
            st.session_state["payoff_df"],
            pd.DataFrame
        )
        and not st.session_state["payoff_df"].empty
    )

    if payoff_exists:

        payoff_df = st.session_state["payoff_df"]

        st.sidebar.success(
            "✅ Payoff Connected"
        )

        st.sidebar.write(
            f"Alternatives: {payoff_df.shape[0]}"
        )

        st.sidebar.write(
            f"Criteria: {payoff_df.shape[1]}"
        )

    else:

        st.sidebar.warning(
            "⚠️ No Payoff Data"
        )

    return menu