# -*- coding: utf-8 -*-
"""styles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHopX6ThFLG9CS4QoZ9OWLgVKWhsSchy
"""

import streamlit as st
from config import COLORS

def load_css():

    st.markdown(f"""
    <style>

    .main {{
        background-color:
        {COLORS['background']};
    }}

    h1, h2, h3, h4, h5, h6 {{
        color:
        {COLORS['primary']} !important;
    }}

    p, div, span, label {{
        color:
        {COLORS['text']} !important;
    }}

    [data-testid="stSidebar"] {{
        background-color:
        {COLORS['secondary']};
    }}

    [data-testid="stSidebar"] * {{
        color: white !important;
    }}

    .stButton > button {{
        background-color:
        {COLORS['primary']};

        color: white !important;

        border-radius: 10px;

        border: none;

        font-weight: bold;
    }}

    .stMetric {{
        background-color: white;

        padding: 15px;

        border-radius: 15px;

        box-shadow:
        0px 2px 10px rgba(0,0,0,0.1);
    }}

    .stDataFrame {{
        border-radius: 15px;
    }}

    </style>
    """, unsafe_allow_html=True)